### PR TITLE
Added Nav Bar

### PR DESCRIPTION
**Pull request by dheeraj0802**
Added Nav Bar.
Navbar is visible at route /header.
Responsiveness have been added and hamburger icon is also working properly.
NewHeader is the react component of navbar present in components folder.
I have added css in style.css.
I have also Included bootstrap.
A screenshot has been attached below:
Screenshot (288)

### CODE REVIEW

**Comment by Ash-exp** [comment]
Your branch has conflicts in the package-lock.json file.
Run this once :
```npm install node-sass@4.14.1 --save```
And commit & push your code 👍🏻

**Comment by dheeraj0802** [comment]
> Your branch has conflicts in the package-lock.json file.
> Run this once :
> `npm install node-sass@4.14.1 --save`
> And commit & push your code 👍🏻

I have run the command and commited the changes.

**Comment by dheeraj0802** [comment]
Mobile View of Website after pressing hamburger button:
Screenshot (293)



Mobile View of Website before pressing hamburger button:
Screenshot (294)

**Comment by Ash-exp** [comment]
I find your element to be quite decent and responsive.. Great job pal👍..!! Appreciate your efforts.!!

**Pull request merged**
