### PR TITLE
Added nav-bar

### PR DESCRIPTION
**Pull request by dheeraj0802**

### CODE REVIEW

**Comment by Ash-exp** [comment]
Please provide the description of the task you have been assigned and mention thee route where you have randered the component (Don't use the landing page route) and make sure you attach the screenshot of the component you have built..!! We appreciate your efforts but these requirements should be achieved inorder to merge your PR..!!

**Comment by dheeraj0802** [comment]
> Please provide the description of the task you have been assigned and mention thee route where you have randered the component (Don't use the landing page route) and make sure you attach the screenshot of the component you have built..!! We appreciate your efforts but these requirements should be achieved inorder to merge your PR..!!

Sure I will do the same

**Review by dheeraj0802 — COMMENTED** [review]
I was given the task of making nav bar.
The nav bar is visible on the route '/header'
I have added header component in components folder.
I have added css in style.css.
I have also Included bootstrap.
Here is a view of navbar:
Screenshot (283)

**Comment by sams14** [comment]
Good job!

**Comment by Ash-exp** [comment]
Your component is good and looks decent. But it's not responsive and the toggle button is also not working. Fix those and raise another PR

**Comment by dheeraj0802** [comment]
Sure I will do it asap

**Review by Ash-exp — COMMENTED** [review]
Not responsive and have over written the existing the header. I appreciate that you used a different route to render and the PR documentation was great..!!

**Comment by dheeraj0802** [comment]
Ok I will make all the changes as you have suggested and will raise a new pr .

**Pull request merged**
