### PR TITLE
added some badges in the README

### LINKED ISSUE #15: add some badges to the Readme file
## Description
add some badges to the top of readme.md file, since the badges will be colorful and more attractive at the top of README.md file than the text the users will like it and after linking the badges it will also help them to navigate to different sections/ webpages like PRs, issues, contributors, etc.

## Describe the solution you'd like

image

I will add some badges at the top and also will add links related to them so that the README.md file will look more interactive and awesome.

### Work under/as

- [x] LGMSOC
- [ ] Contributor

### PR DESCRIPTION
**Pull request by Umesh-01**
## Description
I have added some badges with the links related to them in the README.md file, now after clicking on the badges the user will be redirected to the related section/web page.

This fixes #15 

## Files changed/modified
`README.md`

### Original

image

### Updated

image

### CODE REVIEW

**Comment by Ash-exp** [comment]
Hey @Umesh-01 that's some decent badges you have added..!! I'd appreciate if you can add any badges to each individual sections and beautofy a bit.

**Comment by Ash-exp** [comment]
If possible add a folder structure section and let me know if you need any data regarding it.. Thanks for your contributing !! Once you get done with these we will get your PR merged 👍

**Review by Ash-exp — CHANGES_REQUESTED** [review]
Add badges to individual sections and add the folder structure section 👍

**Comment by Umesh-01** [comment]
@Ash-exp did you mean to add badges in each sub-directory of this repository??
Can you explain a little bit more, I didn't get it??

**Comment by Ash-exp** [comment]
> @Ash-exp did you mean to add badges in each sub-directory of this repository??
> Can you explain a little bit more, I didn't get it??

No not in sub directory but for each headings and sub headings in the readme file if you can add any related badges to it, it would be appreciated 👍

**Comment by Umesh-01** [comment]
> > @Ash-exp did you mean to add badges in each sub-directory of this repository??
> > Can you explain a little bit more, I didn't get it??
> 
> No not in sub directory but for each headings and sub headings in the readme file if you can add any related badges to it, it would be appreciated 👍

okk, I will try but we can't link all these sections like I have done for the badges present at the top of README
that means after clicking on those badges they will look like this--

image

and will not redirect the user to any related webpage or sections as it doesn't exist...

**Comment by Ash-exp** [comment]
> > > @Ash-exp did you mean to add badges in each sub-directory of this repository??
> > > Can you explain a little bit more, I didn't get it??
> > 
> > 
> > No not in sub directory but for each headings and sub headings in the readme file if you can add any related badges to it, it would be appreciated +1
> 
> okk, I will try but we can't link all these sections like I have done for the badges present at the top of README
> that means after clicking on those badges they will look like this--
> 
> image
> 
> and will not redirect the user to any related webpage or sections as it doesn't exist...

Yeah I got you point but that's not what I meant !! I actually needed an decent formatting and along with some non-redirected badges to beautify the readme a bit !! We can still merge your PR, the badges you added are already useful !! Mention if you can decorate the readme individual sections a bit or else we'll proceed an merge it

**Review by Ash-exp — APPROVED** [review]

**Pull request merged**
