### PR TITLE
Create a Banner

### PR DESCRIPTION
**Pull request by vipinRohilla**
i have created a banner

### CODE REVIEW

**Comment by sams14** [comment]
Great work @vipinRohilla . Now for better understanding add screenshot of your development, and render the assigned component in a different route other than the landing page. Don't forget to mention that route you used 
Happy coding

**Comment by vipinRohilla** [comment]
okay I will share all the screenshots for a better understanding, and also take care of the route thing
Happy coding

**Comment by sams14** [comment]
Cool! We'll keep you updated.

**Pull request merged**
